### ISSUE TITLE
is there anything that i can contribute?

### ISSUE THREAD

**Issue by Yaswanth-Mitta** [xcrescent/portfolio_brl_trainees#2]

**Comment by xcrescent** [comment]
Yes you can start contributing tomorrow onwards. I'll update the instructions on how to contribute by today

**Comment by Rahullkumr** [comment]
ok

**Comment by Yaswanth-Mitta** [comment]
@xcrescent for hacktobest contribution you need to create a issue and label it as hacktoberfest , then only our contribution gets valid

**Comment by xcrescent** [comment]
Issues created
